services:
  zig-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"  # Expose to other containers, not to host
    volumes:
      - ./:/app
    working_dir: /app
    command: "zig build -Doptimize=ReleaseSafe run"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d      # Mount nginx config
      - ./static:/usr/share/nginx/html        # Mount your static files
      - ./nginx/ssl:/etc/nginx/ssl            # Mount SSL certificates
    depends_on:
      - zig-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge